### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by bennn** [utahplt/juliacon2023-paper#1]
Add a readme with the basics:

- link to the call for papers (or, abstracts)
- page limit, and whether it includes references
- anoymization rules if any
- deadline

**Comment by ashton314** [comment]
I can't find the deadline anywhere; I did add some links. Submission guidelines are really flexible here. Didn't see anything about anonymization.

Most of the time—it seems—JuliaCon wants you to build the paper inside your library. I like having a separate repo, but we could consider merging.

**Comment by bennn** [comment]
Keep it separate for now & aim for a full paper.

Once we decide what to submit to JuliaCon (abstract or full paper), we can move a copy to the library.
