### ISSUE TITLE
vector graphics

### ISSUE THREAD

**Issue by bennn** [utahplt/juliacon2023-paper#3]
convert all pngs to ps / pdf / eps or svg (the 1st three should work fine with `includegraphics` as-is)

**Comment by ashton314** [comment]
Do you have a format you like best?

**Comment by ashton314** [comment]
Everything is now a PDF—seemed like the simplest option.

The text in the boxes of Figure 2 are actually pictures. I made sure to capture those at a high resolution. I can work on recreating the diagram in TikZ or, or changing the text from a TeX generated diagram to something close; e.g.


![genpropkill-outline_vector](https://github.com/utahplt/juliacon2023-paper/assets/2874507/d1bb2174-e115-454b-bb5e-ef4d858cc25d)

(here are the files; also committed)

[genpropkill-outline_color_vector.pdf](https://github.com/utahplt/juliacon2023-paper/files/12385198/genpropkill-outline_color_vector.pdf)
[genpropkill-outline_vector.pdf](https://github.com/utahplt/juliacon2023-paper/files/12385199/genpropkill-outline_vector.pdf)

**Comment by ashton314** [comment]
And at this point I realized I'm bikeshedding too hard… I just slapped the less-colorful version into the paper.

There is no bitmap. All is vector.
